# Generated by Django 5.2.6 on 2025-10-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('model_type', models.CharField(blank=True, max_length=100, null=True)),
                ('dataset_used', models.CharField(blank=True, max_length=200, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='ai/previews/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/files/')),
                ('waveform_image', models.ImageField(blank=True, null=True, upload_to='audio/waveforms/')),
                ('software_used', models.CharField(blank=True, max_length=100, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CybersecurityProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('exploit_demo', models.FileField(blank=True, null=True, upload_to='cyber/demos/')),
                ('cve_id', models.CharField(blank=True, max_length=50, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('writeup', models.FileField(blank=True, null=True, upload_to='cyber/writeups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('code_snippet', models.TextField(blank=True, null=True)),
                ('repo_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(blank=True)),
                ('detailed_description', models.TextField(blank=True)),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='trading/charts/')),
                ('strategy_used', models.CharField(blank=True, max_length=100, null=True)),
                ('timeframe', models.CharField(blank=True, max_length=50, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
